### ISSUE TITLE
Where is file local-setting.php

### ISSUE THREAD

**Issue by bangnokia** [Goteo/Goteo#104]
i just install goteo 2.0, but i cant find it 
No se encuentra el archivo de configuración local-settings.php, debes crear este archivo en la raiz.
Puedes usar el siguiente código modificado con los credenciales adecuados.

**Comment by cesc1989** [comment]
@bangnokia you need to access index.php , i.e http://localhost/index.php and it will print the code you need to create the local-settings.php file.
