### ISSUE TITLE
Versión del PHP

### ISSUE THREAD

**Issue by yourleader** [Goteo/Goteo#14]
Infiero que este error (Parse error: syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in /home/index.php on line 21)  se debe a la versión de php ya que el código esta correcto.

Ahora bien estoy usando php 5.2.17  probé también con php 5.3.14 y ocurre el mismo error.

¿cuál es la versión en que corre sin problemas?

**Comment by Winjim** [comment]
I would need help on a guide to how you got http://tincup.betaverse.com/ running
