### ISSUE TITLE
Captcha in contact's form is not working

### ISSUE THREAD

**Issue by trsh** [Goteo/Goteo#162]
Besides the problem in topic, I wanted to ASK: I saw a comment in code "// url (this will change on Goteo v3)". So I wanted to ask, If goteo team is working on next version? If it so, will it remain open source? What will change? What and when can we expect?

I really wand to work with this platform, because the incredible features packed in one set, but from other side a) the code isn't updated for a whole Year b) tracked issues are being ignored. Seems like nobody cares about his v2.

Can, please, someone explain something. Don't want to start a new project with a sinking ship :)

**Comment by Goteo** [comment]
Hi there, thanks for forking Goteo, we're actually working on a new version, to be published in September, it will be updated here, under the same license. Have in mind we're a small team and fully busy with refactorization. We also spent lots of energy working on our opendata Api, so at some point we need to take care of the community of reseachers and users starving for an api and the comunity of Developers on the other and sometime it is complicated to do both. Check the api by the way https://developers.goteo.org/ If you speak Japanes there is also an excelent fork here https://github.com/LocalGood Have a good day

**Comment by trsh** [comment]
Can You tell, please, a little bit about the new version in September? Is it a complete rework or just bugfixes? New features? New technologies, maybe a 3rd party Platform?

**Comment by microstudi** [comment]
Hi, I can tell you that the next version of Goteo it's a major refactoring of the code.
The goal is to achieve a more organised way to do things, and do the things in a "modern way".
Things like:
- using composer for 3rd party libraries
- introducing unit tests
- introducing Symfony components and a his routing system
- a full rewrite of the view subsystem using a template system.
- of course, optimizations, bug fixes
-  finally, a development cycle based on github. Meaning that we will publish bug fixes and improvements regularly in github. 
- a standardized way to personalize and add custom modules/plugins to the platform.

We hop also that contributions from the community will be more easily integrated in the current code.

We are working hard on this, and we hope it will be worth-it!

**Comment by trsh** [comment]
Ghhh. Forking and tuning Goteo v2 NOW would be like buying Playstation 2 one month before the 3 one comes out. Life makes it hard for me :)

**Comment by microstudi** [comment]
We know, I'm working hard to release the new version as soon as possible!

**Comment by trsh** [comment]
I thought about it. Your team will have to migrate https://www.goteo.org/ to the new version - right? So maybe a migration plan also will be documented, with all scripts and stuff? Then it's a piece of cake.

**Comment by microstudi** [comment]
well, we'll doing the migration step by step. I don't think it's gonna be very difficult. A sql migration script will be provided. Better documentation as well (hopefully in English). I cannot make any promises but we'll do the our best. Other things related to the server configuration or cron management will require a manual configuration on the server side.

**Comment by trsh** [comment]
Good! Keep in touch. I see the CAPTCHA in contact form is now displaying, so I'am closing this issue.
